### PR TITLE
Pin tornado under 5.0

### PR DESCRIPTION
**Pull request by jsignell**
Tried to run download locally and was running into tornado 5 errors

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jsignell** [comment]
@conda-forge-admin, please rerender

**Comment by jsignell** [comment]
@mcg1969 do you have any opinions on this? I know it is kind of odd to pin something this old.

**Comment by mcg1969** [comment]
I would welcome a fix to allow a newer version of tornado...

**Comment by jsignell** [comment]
Ok just to bring this full circle, anaconda-project master already has the fix, so we are planning to do a release.

**Pull request closed without merging**
